config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/prices'
  post "/home/prices" => 'home/prices'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    require 'net/http'
    require 'json'
   #Grab News Data
    @url = 'https://min-api.cryptocompare.com/data/v2/news/?lang=EN'
    @uri= URI(@url)
    @response  = Net::HTTP.get(@uri)
    @news = JSON.parse(@response)


    #Grab Price Data
    @prices_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,ETH,XRP,BCH,EOS,LTC,ADA,XLM,MIOTA,USDT,TRX,BNB,DOT&tsyms=USD'
    @prices_uri= URI(@prices_url)
    @prices_response= Net::HTTP.get(@prices_uri)
    @prices = JSON.parse(@prices_response)

  end


  def prices
    require 'net/http'
    require 'json'
    @symbol=params[:sym]
    if @symbol
    @symbol=@symbol.upcase

    @quote_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms='+ @symbol +'&tsyms=USD'
    @quote_uri= URI(@quote_url)
    @quote_response= Net::HTTP.get(@quote_uri)
    @quote = JSON.parse(@quote_response)
    end
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Crypto News Network",root_path,class:'navbar-brand' %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
        <% link_to "Get_Prices",home_prices_path,class:'nav-link' %>
          
        </li>
     
      
      </ul>
      <%= form_tag home_prices_path, :method => 'POST', class:"d-flex" do  %>
       
        <%= text_field_tag 'sym', nil,placeholder: "Enter Crypto Symbol" , class: "form-control me-2" %>
        <%= submit_tag 'Lookup ',class:'btn btn-outline-secondary' %>
     
      <% end %>




  
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<br/>
<h4>SAMPLES OF Cryptocurrencies, Please search on any other Cryptocurrencies</h4>
<table class="table table-sm table-striped table-bordered table-hover">
  <thead class="thead-light">
  <tr>
  <th scope="col">Name</th>
  <th scope="col">Price</th>
  <th scope="col">24hr High</th>
  <th scope="col">24hr Low</th>
  <th scope="col">Market Cap</th>
</tr>
</thead>
<tbody>
    <% @prices["DISPLAY"].each do |key, value| %>
     
    

    <tr>
      <td scope="col"><%= key  %></td>
      <td scope="col"><%= value["USD"]["PRICE"] %></td>
      <td scope="col"><%= value["USD"]["HIGHDAY"] %></td>
      <td scope="col"><%= value["USD"]["LOWDAY"] %></td>
      <td scope="col"><%= value["USD"]["MKTCAP"] %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br/>
<h4>Latest News</h4>






<div class="container">
<div class="row">
<% for x in @news["Data"] %>
<div class="col-sm">

<div class="card" style="width: 18rem;">
<img src="<%= x["imageurl"]%>" class="card-img-top" alt="<%= x["source"]%>">
<div class="card-body">
  <h5 class="card-title"> <%= x["title"] %> </h5>
  <p class="card-text"><%= x["body"] %></p>
  <a href="<%= x["url"]%>" class="btn btn-secondary">Read More...</a>
</div>
</div>
<br/>
</div>
<% end %>

</div>
</div>

app/views/home/prices.html.erb
<br/>
<% if @symbol%>
<% if @quote["Response"] %>
  <h4>The CryptoSymbol <%=@symbol%> Doesnot Exist, Please Try Again..</h4>

<%else%>



<table class="table table-sm table-striped table-bordered table-hover">
  <thead class="thead-light">
  <tr>
  <th scope="col">Name</th>
  <th scope="col">Price</th>
  <th scope="col">24hr High</th>
  <th scope="col">24hr Low</th>
  <th scope="col">Market Cap</th>
</tr>
</thead>
<tbody>
    <% @quote["DISPLAY"].each do |key, value| %>
     
    

    <tr>
      <td scope="col"><%= key  %></td>
      <td scope="col"><%= value["USD"]["PRICE"] %></td>
      <td scope="col"><%= value["USD"]["HIGHDAY"] %></td>
      <td scope="col"><%= value["USD"]["LOWDAY"] %></td>
      <td scope="col"><%= value["USD"]["MKTCAP"] %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<%else%>
<h4>Please Enter CryptoSymbol</h4>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptonews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <br/>
  <body>
  <%= render 'home/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>